query branchesQuery($lang: String!) {
  page: pages(where: { title: "Branches", lang: $lang }) {
    edges {
      node {
        branches {
          header {
            title
            text
            image
          }
          activities_title
          events_title
        }
      }
    }
  }
  branches: branches(where: { lang: $lang }) {
    edges {
      node {
        id
        title
      }
    }
  }
}
