query branchQuery($lang: String!, $title: String!) {
  branch: branches(where: { lang: $lang, title: $title }) {
    edges {
      node {
        id
        title
        acf {
          contact_info {
            address_label
            address
            email_label
            email
            phone_number_label
            phone_number
            social_media_label
            social_media {
              facebook
              twitter
              instagram
            }
          }
          activities {
            title
            description
            date_time
            image
          }
          events
        }
      }
    }
  }
}
