query branchQuery($lang: String!, $title: String!) {
  branch: branches(where: { lang: $lang, title: $title }) {
    edges {
      node {
        id
        title
        acf {
          description
          activities {
            title
            description
            date_time
            image
          }
        }
      }
    }
  }
}
