query branchesQuery($lang: String!) {
  page: pages(where: { lang: $lang, title: "Collaborations" }) {
    edges {
      node {
        collaborations {
          header {
            title
            text
            image
            link_button {
              label
            }
          }
          projects_title
          green_banner {
            title
            text
            link_button {
              label
            }
          }
        }
      }
    }
  }
  collaborations(where: { lang: $lang }) {
    edges {
      node {
        id
        title
        acf {
          image
          title
        }
      }
    }
  }
}
