query eventsQuery($lang: String!, $ids: [ID]!) {
  events(where: { in: $ids, lang: $lang }) {
    edges {
      node {
        title
        acf {
          date
          facebook_event
          image
        }
      }
    }
  }
}
